import{i as L,a as v,S as w}from"./assets/vendor-bad0427b.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const b=new URL("/goit-js-hw-12/assets/arrow-icons-a5dab455.svg#icon-left",self.location).href,R=new URL("/goit-js-hw-12/assets/arrow-icons-a5dab455.svg#icon-right",self.location).href,S=new URL("/goit-js-hw-12/assets/error-icon-40fa32d5.svg",self.location).href,d=new URL("/goit-js-hw-12/assets/warning-icon-12913e67.svg",self.location).href,u="user-query",h=document.querySelector(".gallery"),U=document.querySelector(".search-photos"),g=document.querySelector(".loader-wrapper"),l=document.querySelector(".more-btn");let n=1,f=40;const c=(e,s="ERROR",r=S,a="rgba(239, 64, 64, 1)")=>{L.show({title:s,backgroundColor:a,theme:"dark",message:e,position:"topRight",timeout:5e3,iconUrl:r})},m=e=>Math.ceil(e.totalHits/f),y=async e=>(await v.get("https://pixabay.com/api/",{params:{key:"41527103-e0775164a767d3baf6162359a",q:encodeURIComponent(e).replace(/%20/g,"+"),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:n}})).data,p=e=>{const s=e.hits;if(e.totalHits===0)return g.classList.add("visually-hidden"),c("Sorry, there are no images matching your search query. Please, try again!");{const r=s.map(({webformatURL:t,largeImageURL:o,tags:i})=>`
                        <li class="gallery-item">
                            <a class="gallery-link" href="${o}">
                                <img
                                    loading="lazy"
                                    class="gallery-image"
                                    src="${t}"
                                    alt="${i}"
                                />
                            </a>
                        </li>
                        `).join("");h.insertAdjacentHTML("beforeend",r),new w(".gallery a",{navText:[`<svg width="24" height="24"><use href="${b}"></svg>`,`<svg width="24" height="24"><use href="${R}"></svg>`],captionsData:"alt",captionDelay:!1}).refresh(),g.classList.add("visually-hidden")}},I=async()=>{try{n+=1;const e=await y(sessionStorage.getItem(u)),s=m(e);n===s&&(l.classList.add("visually-hidden"),c("The end of collection has been reached","INFO",d,"rgba(167, 166, 145, 1)")),p(e)}catch(e){c(e.message)}},q=async e=>{e.preventDefault(),h.innerHTML="",g.classList.remove("visually-hidden");const s=e.target.elements[0].value.trim().toLowerCase().toString();sessionStorage.setItem(u,s),n=1;const r=await y(s),a=m(r);p(r),n===a?(l.classList.add("visually-hidden"),c("The end of collection has been reached","INFO",d,"rgba(167, 166, 145, 1)")):n<a&&l.classList.remove("visually-hidden"),e.target.reset()};U.addEventListener("submit",q);l.addEventListener("click",I);
//# sourceMappingURL=commonHelpers.js.map
