import{i as p,a as L,S as v}from"./assets/vendor-bad0427b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const w=new URL("../img/icons/arrow-icons.svg#icon-left",self.location).href,b=new URL("../img/icons/arrow-icons.svg#icon-right",self.location).href,S=new URL("/goit-js-hw-12/assets/error-icon-40fa32d5.svg",self.location).href,g="user-query",u=document.querySelector(".gallery"),R=document.querySelector(".search-photos"),c=document.querySelector(".loader-wrapper"),l=document.querySelector(".more-btn");let i=1,m=9;const d=e=>{p.show({title:"ERROR",backgroundColor:"rgba(239, 64, 64, 1)",theme:"dark",message:e,position:"topRight",timeout:5e3,iconUrl:S})},h=e=>Math.ceil(e.totalHits/m),f=async e=>(await L.get("https://pixabay.com/api/",{params:{key:"41527103-e0775164a767d3baf6162359a",q:encodeURIComponent(e).replace(/%20/g,"+"),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m,page:i}})).data,y=e=>{const o=e.hits;if(e.totalHits===0)return c.classList.add("visually-hidden"),d("Sorry, there are no images matching your search query. Please, try again!");{const r=o.map(({webformatURL:t,largeImageURL:s,tags:n})=>`
                        <li class="gallery-item">
                            <a class="gallery-link" href="${s}">
                                <img
                                    loading="lazy"
                                    class="gallery-image"
                                    src="${t}"
                                    alt="${n}"
                                />
                            </a>
                        </li>
                        `).join("");u.insertAdjacentHTML("beforeend",r),new v(".gallery a",{navText:[`<svg width="24" height="24"><use href="${w}"></svg>`,`<svg width="24" height="24"><use href="${b}"></svg>`],captionsData:"alt",captionDelay:!1}).refresh(),c.classList.add("visually-hidden")}},k=async()=>{try{i+=1;const e=await f(sessionStorage.getItem(g)),o=h(e);i===o&&(l.classList.add("visually-hidden"),d("The end of collection has been reached")),y(e)}catch(e){d(e.message)}},q=async e=>{e.preventDefault(),u.innerHTML="",c.classList.remove("visually-hidden");const o=e.target.elements[0].value.trim().toLowerCase().toString();sessionStorage.setItem(g,o),i=1;const r=await f(o),a=h(r);y(r),i===a?l.classList.add("visually-hidden"):i<a&&l.classList.remove("visually-hidden"),e.target.reset()};R.addEventListener("submit",q);l.addEventListener("click",k);
//# sourceMappingURL=commonHelpers.js.map
